### ISSUE TITLE
Implement argument parser

### ISSUE THREAD

**Issue by thiagolrpinho** [rafaelcn/jvm#3] opened 2020-08-24 15:03 UTC
To initialize the virtual machine we have to have an argument parser. That is, an entry algorithm which parses the flag sent to the _njvm_ and initialize it properly.

**Comment by thiagolrpinho** [comment] 2020-09-15 12:22
Done!

**Comment by thiagolrpinho** [comment] 2020-09-15 12:53
Done. Main not compiling thought, need to fix vm_init

**Comment by rafaelcn** [comment] 2020-09-15 12:56
Don't close an issue until you propose a PR as this issue will be closed after the issue is merged.

**Comment by rafaelcn** [comment] 2020-09-15 12:56
This process is done automatically, so don't worry about it. Propose a PR, I will review it and then, after its closure, it will be merged and this issue will be closed.

**Closed** 2020-09-21 13:33 UTC
